{% set name = "mac_alias" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mac_alias-{{ version }}.tar.gz
  sha256: 655906606461754aa80c7acc5672c74d74a1497c649c8f912cb329ca5c6f4ca6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - mac_alias
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://alastairs-place.net/projects/mac_alias
  doc_url: https://mac-alias.readthedocs.io/en/latest/
  summary: Generate and parse Mac OS Alias records from Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
